exercism/wren

exercises/practice/sieve/.docs/instructions.md
exercises/practice/sieve/.meta/config.json
exercises/practice/sieve/.meta/proof.ci.wren
exercises/practice/sieve/LICENSE
exercises/practice/sieve/package.wren
exercises/practice/sieve/sieve.spec.wren
exercises/practice/sieve/sieve.wren

Sieve exercise

---

exercises/practice/binary-search-tree/package.wren
exercises/practice/change/package.wren
exercises/practice/two-bucket/package.wren

fix package names

---

exercises/practice/high-scores/.meta/proof.ci.wren
exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/high-scores.spec.wren

high-scores: Implement missing test cases

---

config.json
exercises/practice/wordy/.docs/instructions.md
exercises/practice/wordy/.meta/config.json
exercises/practice/wordy/.meta/proof.ci.wren
exercises/practice/wordy/.meta/tests.toml
exercises/practice/wordy/LICENSE
exercises/practice/wordy/package.wren
exercises/practice/wordy/wordy.spec.wren
exercises/practice/wordy/wordy.wren

Add Wordy Exercise to Wren

---

config.json

Config missing for sieve exercise

---

docs/ABOUT.md

Fixed spelling errors, punctuation inconsistencies, and a dead link

Update ABOUT.md to fix SPAG errors

---

config.json
exercises/practice/grep/.docs/instructions.append.md
exercises/practice/grep/.docs/instructions.md
exercises/practice/grep/.meta/config.json
exercises/practice/grep/.meta/proof.ci.wren
exercises/practice/grep/.meta/tests.toml
exercises/practice/grep/LICENSE
exercises/practice/grep/grep.spec.wren
exercises/practice/grep/grep.wren
exercises/practice/grep/package.wren

Hi Josh, it's been a while.
I noticed some new activity on the track and realized I have some dusty exercise implementations that never got pushed.

Grep exercise

---

config.json
exercises/practice/square-root/.docs/instructions.md
exercises/practice/square-root/.meta/config.json
exercises/practice/square-root/.meta/proof.ci.wren
exercises/practice/square-root/.meta/tests.toml
exercises/practice/square-root/LICENSE
exercises/practice/square-root/package.wren
exercises/practice/square-root/square-root.spec.wren
exercises/practice/square-root/square-root.wren

Changes to be committed:
modified:   ../../config.json
new file:   square-root/.docs/instructions.md
new file:   square-root/.meta/config.json
new file:   square-root/.meta/proof.ci.wren
new file:   square-root/.meta/tests.toml
new file:   square-root/LICENSE
new file:   square-root/package.wren
new file:   square-root/square-root.spec.wren
new file:   square-root/square-root.wren

adds square-root practice exercise

---

config.json
exercises/practice/rectangles/.docs/instructions.md
exercises/practice/rectangles/.meta/config.json
exercises/practice/rectangles/.meta/proof.ci.wren
exercises/practice/rectangles/.meta/tests.toml
exercises/practice/rectangles/package.wren
exercises/practice/rectangles/rectangles.spec.wren
exercises/practice/rectangles/rectangles.wren

I'll stick to the "desirables" list.

Rectangles exercise

---

exercises/practice/clock/package.wren
exercises/practice/complex-numbers/package.wren
exercises/practice/grep/package.wren
exercises/practice/isogram/package.wren
exercises/practice/rational-numbers/package.wren

run '''for exercise in *; do sed -e "s/-wren-track/\/${exercise}/g" -i "$exercise"/package.wren; done'''
fixes #105

tidy package files to contain exercise name

---

exercises/practice/pig-latin/package.wren
exercises/practice/spiral-matrix/package.wren
scripts/ci

As mentioned in #105 .
After it gets merged and this gets rebased, CI will pass.

validate package name; script improvements

---

config.json
exercises/practice/simple-cipher/.docs/instructions.md
exercises/practice/simple-cipher/.meta/config.json
exercises/practice/simple-cipher/.meta/proof.ci.wren
exercises/practice/simple-cipher/.meta/tests.toml
exercises/practice/simple-cipher/package.wren
exercises/practice/simple-cipher/simple-cipher.spec.wren
exercises/practice/simple-cipher/simple-cipher.wren

closes #118 
Uses the empty stub class.

Simple Cipher exercise

---

.github/workflows/ci.yml

CI: pin runner

---

exercises/practice/dnd-character/dnd-character.wren

For cross-reference, here is [the related forum post](https://forum.exercism.org/t/wren-d-d-character-wrong-stub/8711/3).

Fix dnd-character stub

---

config.json
exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
exercises/practice/parallel-letter-frequency/.docs/instructions.md
exercises/practice/parallel-letter-frequency/.meta/config.json
exercises/practice/parallel-letter-frequency/.meta/proof.ci.wren
exercises/practice/parallel-letter-frequency/.meta/tests.toml
exercises/practice/parallel-letter-frequency/LICENSE
exercises/practice/parallel-letter-frequency/package.wren
exercises/practice/parallel-letter-frequency/parallel-letter-frequency.spec.wren
exercises/practice/parallel-letter-frequency/parallel-letter-frequency.wren

This also adds the "files" section of the track config.json -- https://exercism.org/docs/building/tracks/config-json#h-files
Of note: this uses concurrency but is not really "parallel" processing.

Add parallel-letter-frequency exercise

---

config.json
exercises/practice/binary-search/.docs/instructions.md
exercises/practice/binary-search/.docs/introduction.md
exercises/practice/binary-search/.meta/config.json
exercises/practice/binary-search/.meta/proof.ci.wren
exercises/practice/binary-search/.meta/tests.toml
exercises/practice/binary-search/LICENSE
exercises/practice/binary-search/binary-search.spec.wren
exercises/practice/binary-search/binary-search.wren
exercises/practice/binary-search/package.wren

Add binary-search

---

config.json
exercises/practice/food-chain/.docs/instructions.append.md
exercises/practice/food-chain/.docs/instructions.md
exercises/practice/food-chain/.meta/config.json
exercises/practice/food-chain/.meta/proof.ci.wren
exercises/practice/food-chain/.meta/tests.toml
exercises/practice/food-chain/LICENSE
exercises/practice/food-chain/food-chain.spec.wren
exercises/practice/food-chain/food-chain.wren
exercises/practice/food-chain/package.wren

Note that there is an instructions.append doc.

Add food-chain exercise

---

exercises/practice/zebra-puzzle/.meta/proof.ci.wren

Ukranian => Ukrainian

---

config.json

The exercises have replaced by [list-ops](https://github.com/exercism/problem-specifications/issues/129), [bottle-song](https://github.com/exercism/problem-specifications/issues/2066), [all-your-base](https://github.com/exercism/problem-specifications/issues/279) 
resolves #227

Deprecate accumulate, beer-song, binary exercises

---

exercises/practice/bob/.meta/tests.toml
exercises/practice/bob/bob.spec.wren

Sync bob test case

---

config.json

wren has no builtin date handling functionality.

Forego date-related exercises

---

config.json
exercises/practice/flower-field/.docs/instructions.md
exercises/practice/flower-field/.docs/introduction.md
exercises/practice/flower-field/.meta/config.json
exercises/practice/flower-field/.meta/proof.ci.wren
exercises/practice/flower-field/.meta/tests.toml
exercises/practice/flower-field/LICENSE
exercises/practice/flower-field/flower-field.spec.wren
exercises/practice/flower-field/flower-field.wren
exercises/practice/flower-field/package.wren

Add flower-field
